# Generated by Django 6.1.1 on 2026-09-15 09:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_name', models.CharField(max_length=255)),
                ('supplier_phone', models.CharField(max_length=50)),
                ('state', models.CharField(default='Maharashtra', max_length=100)),
                ('variety', models.CharField(default='nashik_red', max_length=100)),
                ('grade', models.CharField(choices=[('Grade A', 'Grade A (Export Benchmark)'), ('Grade B', 'Grade B (Standard Market)'), ('Grade C', 'Grade C (Secondary Quality)'), ('Reject', 'Reject (Sub-standard)')], default='Grade A', max_length=20)),
                ('size_class', models.CharField(choices=[('Small', 'Small (< 40mm)'), ('Medium', 'Medium (40-60mm)'), ('Large', 'Large (60-80mm)'), ('Extra Large', 'Extra Large (> 80mm)')], default='Medium', max_length=30)),
                ('moisture', models.FloatField(default=12.0, help_text='Moisture content percentage')),
                ('sprouting', models.FloatField(default=0.0, help_text='Sprouting rate percentage')),
                ('damage', models.FloatField(default=0.0, help_text='Mechanical cuts & damage percentage')),
                ('doubles', models.FloatField(default=0.0, help_text='Doubles and split bulb percentage')),
                ('inspector_name', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('computed_score', models.IntegerField(default=100)),
                ('quality_status', models.CharField(choices=[('CERTIFIED', 'Certified'), ('STANDARD', 'Standard'), ('CONDITIONAL', 'Conditional'), ('REJECTED', 'Rejected')], default='CERTIFIED', max_length=30)),
            ],
            options={
                'verbose_name': 'Onion Assessment',
                'verbose_name_plural': 'Onion Assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='assessments/%Y/%m/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='grading.assessment')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
