# Generated by Django 6.1.1 on 2026-09-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='lot_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True),
        ),
    ]
