# Generated by Django 6.1.1 on 2026-09-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_alter_assessment_lot_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectReferenceSample',
            fields=[
                ('sample_id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=100)),
                ('class_tag', models.CharField(max_length=100)),
                ('tag_bg', models.CharField(default='bg-rose-950/85 text-rose-200 border-rose-700', max_length=255)),
                ('badge_bg', models.CharField(default='bg-amber-900/85 text-amber-200 border-amber-700', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='samples/')),
                ('image_url', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Defect Reference Sample',
                'verbose_name_plural': 'Defect Reference Samples',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OnionVariety',
            fields=[
                ('code', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('variety_type', models.CharField(default='Rabi / Storage', max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('characteristics', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='varieties/')),
                ('image_url', models.CharField(blank=True, default='', max_length=500)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Onion Variety',
                'verbose_name_plural': 'Onion Varieties',
                'ordering': ['order', 'name'],
            },
        ),
    ]
